### ISSUE TITLE
Website Analysis TODOS

### ISSUE THREAD

**Issue by wam82** [sfhelmet/InterestFreeCondos#88]
1. Make Navigation bar and make site navigateable ( #43 )

- [x] Done?

2. Styling of pages like Profile Page (WAM)

- [ ]  Done?

3. Fix Google Login as it is broken (Done - #92 )

- [x]  Done?

4. Make the PropertyDetails page which shows details of specific property based on user 

- [ ]  Done?

5. Renter Home page is missing (WAM)

- [ ]  Done?

6. View more functionality in home page 

- [ ]  Done?

7. Profile Page has no functionality for other "My X" features like My requests, My reservations, etc.  (These were removed and made into their own pages)

- [x]  Done?

8. Profile picture uploading doesn't really associate a profile picture to a user just uploads it which can be problematic if a diff user signs in (Done - #92 )

- [x]  Done?

9. Lots of missing functionality on the profile page like the discard and save changes buttons which have no functionality at all  (Done - #94 )

- [x]  Done?

10. A lot of links aren't "protected" meaning that we don't run checks to see if a user is authenticated before allowing access. --> Should be easily fixed by switching the protected variable in routes.js to true (Done - #94 ) 

- [x]  Done?

11. The financials page has terrible styling where some text is white over a white background and buttons are off-set ( #43 Patch )

- [x]  Done?

12. Extra checking is needed to access pages like the financial or request-handling pages because only management should access these pages @wam82 can you confirm this? 

- [ ]  Done?

13. If the public-home page is going to be the page for new users who aren't condo owners, condo renters, management i.e a user with no registration key then this page needs to provide more info to explain this to the user (WAM)

- [ ]  Done?

14. Is the /token route even needed? If so this needs to be hidden because only companies should be able to access it  (Done - Fixed in #94 )

- [x]  Done?

15. Ensure that the styling is consistent across all pages 

- [ ]  Done?

16. When creating properties, there is no associated condo owner to them i.e no ID is paired with property to say who created itffinan

- [ ] Done?

**Comment by DanielC2001** [comment]
TODOs:

1. Make Navigation bar and make site navigateable
2. Styling of pages like Profile Page
3. Fix Google Login as it is broken
4. Make the PropertyDetails page which shows details of specific property based on user
5. Renter Home page is missing
6. View more functionality in home page

**Comment by DanielC2001** [comment]
New TODOs:
1. Profile Page has no functionality for other "My X" features like My requests, My reservations, etc.
2. Profile picture uploading doesn't really associate a profile picture to a user just uploads it which can be problematic if a diff user signs in
3.  Lots of missing functionality on the profile page like the discard and save changes buttons which have no functionality at all
4.  A lot of links aren't "protected" meaning that we don't run checks to see if a user is authenticated before allowing access. --> Should be easily fixed by switching the `protected` variable in `routes.js` to true
5. The financials page has terrible styling where some text is white over a white background and buttons are off-set
6. Extra checking is needed to access pages like the financial or request-handling pages because only management should access these pages @wam82 can you confirm this?
7. If the public-home page is going to be the page for new users who aren't condo owners, condo renters, management i.e a user with no registration key then this page needs to provide more info to explain this to the user
8. Is the /token route even needed? If so this needs to be hidden because only companies should be able to access it

Lastly, before we begin working on these TODOs we must be very clear with the models for things like users and properties because several of us will be working on things that may overlap therefore we need consistency.

**Comment by wam82** [comment]
@DanielC2001 Indeed only specific users should be able to access the specifc pages you mentioned. However, I do not remember which user can access what so we should verify with the reqs. I also added all the todos in the orignal comment so it's easier to reference as we are working on them. You can edit the comment to attribute yourself some of the todos
